INSERT INTO acc_gl_account(id,name,parent_id,hierarchy,gl_code,disabled,manual_journal_entries_allowed,account_usage,classification_enum,tag_id,description) VALUES
('1','Salary Mobilization',NULL,'.','M_Sal','0','1','1','5',13,NULL),
('2','Salary Loan Servicing',NULL,'.','LS_Sal','0','1','1','5',14,NULL),
('3','Salary Investment',NULL,'.','I_Sal','0','1','1','5',15,NULL),
('4','Salary Overheads',NULL,'.','O_Sal','0','1','1','5',16,NULL),
('5','Salary Provisions',NULL,'.','P_Sal','0','1','1','5',17,NULL),
('6','Felicitator Charges',NULL,'.','BF_Chrg','0','1','1','5',18,NULL),
('7','Repairs & Maintanence',NULL,'.','O_R&M','0','1','1','5',17,NULL),
('8','Meetings',NULL,'.','O_Meet','0','1','1','5',17,NULL),
('9','Rent',NULL,'.','O_Rent','0','1','1','5',17,NULL),
('10','Bills',NULL,'.','O_Bills','0','1','1','5',17,NULL),
('11','A-Mobilization',NULL,'.','A_Mob','0','1','1','5',13,NULL),
('12','A-Loan Servicing',NULL,'.','A_LON','0','1','1','5',14,NULL),
('13','A-Investment',NULL,'.','A_INV','0','1','1','5',15,NULL),
('14','B-Loan Servicing',NULL,'.','B_LON','0','1','1','5',14,NULL),
('15','C-Investment',NULL,'.','C_INV','0','1','1','5',15,NULL),
('16','D-Overheads',NULL,'.','D_OVR','0','1','1','5',16,NULL),
('17','D-Loan Servicing',NULL,'.','D_Serv','0','1','1','5',14,NULL),
('18','C-Loan Servicing',NULL,'.','C_Serv','0','1','1','5',14,NULL),
('19','BF Mobilisation Cost',NULL,'.','BF_M_Chrg','0','1','1','5',13,NULL);