
--
-- Data for table `m_portfolio_command_source`
--

INSERT INTO `m_portfolio_command_source` VALUES 
(8,'CREATE','LOANPRODUCT',NULL,NULL,NULL,NULL,NULL,'/loanproducts/template',1,NULL,'{\"currencyCode\":\"INR\",\"includeInBorrowerCycle\":\"false\",\"useBorrowerCycle\":\"false\",\"digitsAfterDecimal\":\"2\",\"inMultiplesOf\":\"0\",\"repaymentFrequencyType\":2,\"interestRateFrequencyType\":2,\"amortizationType\":1,\"interestType\":0,\"interestCalculationPeriodType\":1,\"transactionProcessingStrategyId\":1,\"principalVariationsForBorrowerCycle\":[],\"interestRateVariationsForBorrowerCycle\":[],\"numberOfRepaymentVariationsForBorrowerCycle\":[],\"multiDisburseLoan\":\"false\",\"accountingRule\":\"1\",\"daysInYearType\":1,\"daysInMonthType\":1,\"isInterestRecalculationEnabled\":false,\"preClosureInterestCalculationStrategy\":1,\"isLinkedToFloatingInterestRates\":false,\"allowVariableInstallments\":false,\"name\":\"Demand Loan\",\"shortName\":\"DL\",\"description\":\"Demand Loan\",\"installmentAmountInMultiplesOf\":\"10\",\"minPrincipal\":\"1000\",\"principal\":\"10000\",\"maxPrincipal\":\"1000000\",\"minNumberOfRepayments\":\"10\",\"numberOfRepayments\":\"100\",\"maxNumberOfRepayments\":\"1000\",\"minInterestRatePerPeriod\":\"0\",\"interestRatePerPeriod\":\"0\",\"maxInterestRatePerPeriod\":\"0\",\"repaymentEvery\":\"1\",\"paymentChannelToFundSourceMappings\":[],\"feeToIncomeAccountMappings\":[],\"penaltyToIncomeAccountMappings\":[],\"charges\":[{\"id\":1}],\"allowAttributeOverrides\":{\"amortizationType\":false,\"interestType\":false,\"transactionProcessingStrategyId\":false,\"interestCalculationPeriodType\":false,\"inArrearsTolerance\":false,\"repaymentEvery\":false,\"graceOnPrincipalAndInterestPayment\":false,\"graceOnArrearsAgeing\":false},\"locale\":\"en\",\"dateFormat\":\"dd MMMM yyyy\"}',1,'2018-01-15 21:10:39',NULL,NULL,1,NULL,NULL),
(9,'CREATE','LOANPRODUCT',NULL,NULL,NULL,NULL,NULL,'/loanproducts/template',2,NULL,'{\"currencyCode\":\"INR\",\"includeInBorrowerCycle\":\"false\",\"useBorrowerCycle\":\"false\",\"digitsAfterDecimal\":\"2\",\"inMultiplesOf\":\"0\",\"repaymentFrequencyType\":2,\"interestRateFrequencyType\":2,\"amortizationType\":1,\"interestType\":0,\"interestCalculationPeriodType\":1,\"transactionProcessingStrategyId\":1,\"principalVariationsForBorrowerCycle\":[],\"interestRateVariationsForBorrowerCycle\":[],\"numberOfRepaymentVariationsForBorrowerCycle\":[],\"multiDisburseLoan\":\"false\",\"accountingRule\":\"1\",\"daysInYearType\":1,\"daysInMonthType\":1,\"isInterestRecalculationEnabled\":false,\"preClosureInterestCalculationStrategy\":1,\"isLinkedToFloatingInterestRates\":false,\"allowVariableInstallments\":false,\"name\":\"Short-term Business Loan\",\"shortName\":\"STBL\",\"description\":\"Short-term Business Loan\",\"installmentAmountInMultiplesOf\":\"10\",\"minPrincipal\":\"1000\",\"principal\":\"10000\",\"maxPrincipal\":\"1000000\",\"minNumberOfRepayments\":\"10\",\"numberOfRepayments\":\"100\",\"maxNumberOfRepayments\":\"1000\",\"minInterestRatePerPeriod\":\"0\",\"interestRatePerPeriod\":\"0\",\"maxInterestRatePerPeriod\":\"0\",\"repaymentEvery\":\"1\",\"paymentChannelToFundSourceMappings\":[],\"feeToIncomeAccountMappings\":[],\"penaltyToIncomeAccountMappings\":[],\"charges\":[],\"allowAttributeOverrides\":{\"amortizationType\":false,\"interestType\":false,\"transactionProcessingStrategyId\":false,\"interestCalculationPeriodType\":false,\"inArrearsTolerance\":false,\"repaymentEvery\":false,\"graceOnPrincipalAndInterestPayment\":false,\"graceOnArrearsAgeing\":false},\"locale\":\"en\",\"dateFormat\":\"dd MMMM yyyy\"}',1,'2018-01-15 21:11:39',NULL,NULL,1,NULL,NULL),
(10,'CREATE','LOANPRODUCT',NULL,NULL,NULL,NULL,NULL,'/loanproducts/template',3,NULL,'{\"currencyCode\":\"INR\",\"includeInBorrowerCycle\":\"false\",\"useBorrowerCycle\":\"false\",\"digitsAfterDecimal\":\"2\",\"inMultiplesOf\":\"0\",\"repaymentFrequencyType\":2,\"interestRateFrequencyType\":2,\"amortizationType\":1,\"interestType\":0,\"interestCalculationPeriodType\":1,\"transactionProcessingStrategyId\":1,\"principalVariationsForBorrowerCycle\":[],\"interestRateVariationsForBorrowerCycle\":[],\"numberOfRepaymentVariationsForBorrowerCycle\":[],\"multiDisburseLoan\":\"false\",\"accountingRule\":\"1\",\"daysInYearType\":1,\"daysInMonthType\":1,\"isInterestRecalculationEnabled\":false,\"preClosureInterestCalculationStrategy\":1,\"isLinkedToFloatingInterestRates\":false,\"allowVariableInstallments\":false,\"name\":\"Mid-term Business Loan\",\"shortName\":\"MTBL\",\"description\":\"Mid-term Business Loan\",\"installmentAmountInMultiplesOf\":\"10\",\"minPrincipal\":\"1000\",\"principal\":\"10000\",\"maxPrincipal\":\"1000000\",\"minNumberOfRepayments\":\"10\",\"numberOfRepayments\":\"100\",\"maxNumberOfRepayments\":\"1000\",\"minInterestRatePerPeriod\":\"0\",\"interestRatePerPeriod\":\"0\",\"maxInterestRatePerPeriod\":\"0\",\"repaymentEvery\":\"1\",\"paymentChannelToFundSourceMappings\":[],\"feeToIncomeAccountMappings\":[],\"penaltyToIncomeAccountMappings\":[],\"charges\":[],\"allowAttributeOverrides\":{\"amortizationType\":false,\"interestType\":false,\"transactionProcessingStrategyId\":false,\"interestCalculationPeriodType\":false,\"inArrearsTolerance\":false,\"repaymentEvery\":false,\"graceOnPrincipalAndInterestPayment\":false,\"graceOnArrearsAgeing\":false},\"locale\":\"en\",\"dateFormat\":\"dd MMMM yyyy\"}',1,'2018-01-15 21:13:11',NULL,NULL,1,NULL,NULL),
(11,'CREATE','LOANPRODUCT',NULL,NULL,NULL,NULL,NULL,'/loanproducts/template',4,NULL,'{\"currencyCode\":\"INR\",\"includeInBorrowerCycle\":\"false\",\"useBorrowerCycle\":\"false\",\"digitsAfterDecimal\":\"2\",\"inMultiplesOf\":\"0\",\"repaymentFrequencyType\":2,\"interestRateFrequencyType\":2,\"amortizationType\":1,\"interestType\":0,\"interestCalculationPeriodType\":1,\"transactionProcessingStrategyId\":1,\"principalVariationsForBorrowerCycle\":[],\"interestRateVariationsForBorrowerCycle\":[],\"numberOfRepaymentVariationsForBorrowerCycle\":[],\"multiDisburseLoan\":\"false\",\"accountingRule\":\"1\",\"daysInYearType\":1,\"daysInMonthType\":1,\"isInterestRecalculationEnabled\":false,\"preClosureInterestCalculationStrategy\":1,\"isLinkedToFloatingInterestRates\":false,\"allowVariableInstallments\":false,\"name\":\"Business Loan\",\"shortName\":\"BL\",\"description\":\"Business Loan\",\"installmentAmountInMultiplesOf\":\"10\",\"minPrincipal\":\"1000\",\"principal\":\"10000\",\"maxPrincipal\":\"1000000\",\"minNumberOfRepayments\":\"10\",\"numberOfRepayments\":\"100\",\"maxNumberOfRepayments\":\"1000\",\"minInterestRatePerPeriod\":\"0\",\"interestRatePerPeriod\":\"0\",\"maxInterestRatePerPeriod\":\"0\",\"repaymentEvery\":\"1\",\"paymentChannelToFundSourceMappings\":[],\"feeToIncomeAccountMappings\":[],\"penaltyToIncomeAccountMappings\":[],\"charges\":[],\"allowAttributeOverrides\":{\"amortizationType\":false,\"interestType\":false,\"transactionProcessingStrategyId\":false,\"interestCalculationPeriodType\":false,\"inArrearsTolerance\":false,\"repaymentEvery\":false,\"graceOnPrincipalAndInterestPayment\":false,\"graceOnArrearsAgeing\":false},\"locale\":\"en\",\"dateFormat\":\"dd MMMM yyyy\"}',1,'2018-01-15 21:14:11',NULL,NULL,1,NULL,NULL),
(12,'CREATE','LOANPRODUCT',NULL,NULL,NULL,NULL,NULL,'/loanproducts/template',5,NULL,'{\"currencyCode\":\"INR\",\"includeInBorrowerCycle\":\"false\",\"useBorrowerCycle\":\"false\",\"digitsAfterDecimal\":\"2\",\"inMultiplesOf\":\"0\",\"repaymentFrequencyType\":2,\"interestRateFrequencyType\":2,\"amortizationType\":1,\"interestType\":0,\"interestCalculationPeriodType\":1,\"transactionProcessingStrategyId\":1,\"principalVariationsForBorrowerCycle\":[],\"interestRateVariationsForBorrowerCycle\":[],\"numberOfRepaymentVariationsForBorrowerCycle\":[],\"multiDisburseLoan\":\"false\",\"accountingRule\":\"1\",\"daysInYearType\":1,\"daysInMonthType\":1,\"isInterestRecalculationEnabled\":false,\"preClosureInterestCalculationStrategy\":1,\"isLinkedToFloatingInterestRates\":false,\"allowVariableInstallments\":false,\"name\":\"Morabaha Loan\",\"shortName\":\"ML\",\"description\":\"Morabaha Loan\",\"installmentAmountInMultiplesOf\":\"10\",\"minPrincipal\":\"1000\",\"principal\":\"10000\",\"maxPrincipal\":\"1000000\",\"minNumberOfRepayments\":\"10\",\"numberOfRepayments\":\"100\",\"maxNumberOfRepayments\":\"1000\",\"minInterestRatePerPeriod\":\"0\",\"interestRatePerPeriod\":\"0\",\"maxInterestRatePerPeriod\":\"0\",\"repaymentEvery\":\"1\",\"paymentChannelToFundSourceMappings\":[],\"feeToIncomeAccountMappings\":[],\"penaltyToIncomeAccountMappings\":[],\"charges\":[],\"allowAttributeOverrides\":{\"amortizationType\":false,\"interestType\":false,\"transactionProcessingStrategyId\":false,\"interestCalculationPeriodType\":false,\"inArrearsTolerance\":false,\"repaymentEvery\":false,\"graceOnPrincipalAndInterestPayment\":false,\"graceOnArrearsAgeing\":false},\"locale\":\"en\",\"dateFormat\":\"dd MMMM yyyy\"}',1,'2018-01-15 21:14:56',NULL,NULL,1,NULL,NULL);



--
-- Data for table `m_product_loan`
--
INSERT INTO `m_product_loan` VALUES 
(1,'DL','INR',2,0,10000.000000,1000.000000,1000000.000000,NULL,'Demand Loan','Demand Loan',NULL,'\0','\0',0.000000,0.000000,0.000000,2,0.000000,0,1,0,1,2,100,10,1000,NULL,NULL,NULL,1,1,1,NULL,0,0,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,0,NULL,0,0.00,0,0,10.000000),
(2,'STBL','INR',2,0,10000.000000,1000.000000,1000000.000000,NULL,'Short-term Business Loan','Short-term Business Loan',NULL,'\0','\0',0.000000,0.000000,0.000000,2,0.000000,0,1,0,1,2,100,10,1000,NULL,NULL,NULL,1,1,1,NULL,0,0,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,0,NULL,0,0.00,0,0,10.000000),
(3,'MTBL','INR',2,0,10000.000000,1000.000000,1000000.000000,NULL,'Mid-term Business Loan','Mid-term Business Loan',NULL,'\0','\0',0.000000,0.000000,0.000000,2,0.000000,0,1,0,1,2,100,10,1000,NULL,NULL,NULL,1,1,1,NULL,0,0,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,0,NULL,0,0.00,0,0,10.000000),
(4,'BL','INR',2,0,10000.000000,1000.000000,1000000.000000,NULL,'Business Loan','Business Loan',NULL,'\0','\0',0.000000,0.000000,0.000000,2,0.000000,0,1,0,1,2,100,10,1000,NULL,NULL,NULL,1,1,1,NULL,0,0,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,0,NULL,0,0.00,0,0,10.000000),
(5,'ML','INR',2,0,10000.000000,1000.000000,1000000.000000,NULL,'Morabaha Loan','Morabaha Loan',NULL,'\0','\0',0.000000,0.000000,0.000000,2,0.000000,0,1,0,1,2,100,10,1000,NULL,NULL,NULL,1,1,1,NULL,0,0,NULL,NULL,0,NULL,NULL,NULL,NULL,1,1,0,NULL,0,0.00,0,0,10.000000);


--
-- Data for table `m_product_loan_charge`
--
INSERT INTO `m_product_loan_charge` VALUES (1,1);


--
-- Data for table `m_product_loan_configurable_attributes`
--
INSERT INTO `m_product_loan_configurable_attributes` VALUES 
(1,1,0,0,0,0,0,0,0,0),
(2,2,0,0,0,0,0,0,0,0),
(3,3,0,0,0,0,0,0,0,0),
(4,4,0,0,0,0,0,0,0,0),
(5,5,0,0,0,0,0,0,0,0);


